--- cargo-crates/libgit2-sys-0.18.0+1.9.0/Cargo.toml.orig	1970-01-01 00:00:01 UTC
+++ cargo-crates/libgit2-sys-0.18.0+1.9.0/Cargo.toml
@@ -58,7 +58,6 @@ vendored = []
 ssh = ["libssh2-sys"]
 ssh_key_from_memory = []
 vendored = []
-vendored-openssl = ["openssl-sys/vendored"]
 zlib-ng-compat = [
     "libz-sys/zlib-ng",
     "libssh2-sys?/zlib-ng-compat",
