# Created by: Yoichi Asai <yatt@msc.biglobe.ne.jp>
# $FreeBSD: audio/timidity++-gtk/Makefile 2482 2020-05-03 21:35:50Z  $

PKGNAMESUFFIX=	-gtk

MAINTAINER=	ports@FreeBSD.org
COMMENT=	Gtk interface for TiMidity++

MASTERDIR=	${.CURDIR}/../../audio/timidity++

PLIST_FILES=	bin/${LINK} ${TIMID_LIBDIR}/if_gtk.so

.include "${MASTERDIR}/Makefile"
