PORTNAME=	bsdsensors
PORTVERSION=	0.1
CATEGORIES=	sysutils

MAINTAINER=	kdeguchi@sz.tokoha-u.ac.jp
COMMENT=	Getting sensor values on FreeBSD

LIB_DEPENDS=	libprotobuf.so:devel/protobuf \
		libgflags.so:deve/gflags \
		libglog.so:devel/glog

USES=		cmake:noninja

USE_GITHUB=	yes
GH_ACCOUNT=	HenryHu
GH_TAGNAME=	87754d9

.include <bsd.port.mk>
