# $FreeBSD: x11-themes/flat-remix-icon/Makefile 2588 2020-06-30 23:26:45Z  $

PORTNAME=	flat-remix
PORTVERSION=	20200623
CATEGORIES=	x11-themes
PKGNAMESUFFIX=	-icon

MAINTAINER=	kdeguchi@sz.tokoha-u.ac.jp
COMMENT=	Flat-Remix ICON theme

LICENSE=	GPLv3

USES=	gmake gnome

USE_GITHUB=	yes
GH_ACCOUNT=	daniruiz
GH_PROJECT=	Flat-Remix

INSTALLS_ICONS=	yes

NO_BUILD=	yes

WRKSRC=	${WRKDIR}/${PORTNAME}-${PORTVERSION}

.include <bsd.port.mk>
