# Created by: Yoichi Asai <yatt@msc.biglobe.ne.jp>
# $FreeBSD: audio/timidity++-xskin/Makefile 2482 2020-05-03 21:35:50Z  $

PKGNAMESUFFIX=	-xskin

MAINTAINER=	ports@FreeBSD.org
COMMENT=	X11AMP skin interface for TiMidity++

OPTIONS_DEFINE=	DOCS

MASTERDIR=	${.CURDIR}/../../audio/timidity++

.include "${MASTERDIR}/Makefile"
