# Created by: Yoichi Asai <yatt@msc.biglobe.ne.jp>
# $FreeBSD: audio/timidity++-tcltk/Makefile 2482 2020-05-03 21:35:50Z  $

PKGNAMESUFFIX=	-tcltk

MAINTAINER=	ports@FreeBSD.org
COMMENT=	Tcl/Tk interface for TiMidity++

BROKEN=		fails to build: /bin/sh: tclsh: not found

OPTIONS_DEFINE=	DOCS

MASTERDIR=	${.CURDIR}/../../audio/timidity++

.include "${MASTERDIR}/Makefile"
