PKGNAMESUFFIX=	-common

COMMENT=	Fcitx support for Qt (common files)

FLAVORS=	# empty
FLAVOR=	# empty

CMAKE_OFF=	ENABLE_QT4 ENABLE_QT5 ENABLE_QT6

MASTERDIR=	${.CURDIR}/../fcitx5-qt

NO_ARCH=	yes

PLIST=	${MASTERDIR}/pkg-plist.common

.include "${MASTERDIR}/Makefile"
