# Created by: Daichi GOTO <daichi@FreeBSD.org>
# $FreeBSD: japanese/fcitx-mozc/Makefile 2487 2020-05-04 00:16:42Z  $

PKGNAMEPREFIX=	ja-fcitx-

COMMENT=	Mozc engine for Fcitx

DATADIR=	${PREFIX}/share/fcitx/${PORTNAME}

MASTERDIR=	${.CURDIR}/../../japanese/mozc-server
FILESDIR=	${.CURDIR}/files
SUB_FILES=	pkg-message

BUILD_MOZC_LIST=	fcitx_mozc

.include "${MASTERDIR}/Makefile"
