# $FreeBSD: math/p5-Math-RungeKutta/Makefile 453 2013-10-09 22:01:50Z  $

PORTNAME=	Math-RungeKutta
PORTVERSION=	1.07
PORTREVISION=	1
CATEGORIES=	math perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	p5-

MAINTAINER=	kdeguchi@sz.tokoha-u.ac.jp
COMMENT=	Perl module for Runge-Kutta mathod

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
