# $FreeBSD: emulators/virtualbox-ose-additions-nox11/Makefile 2263 2020-01-17 06:31:56Z  $

PKGNAMESUFFIX=	-additions-nox11

OPTIONS_EXCLUDE=	DBUS DEBUG OPENGL X11

MASTERDIR=	${.CURDIR}/../virtualbox-ose-additions

.include "${MASTERDIR}/Makefile"
