DISTFILES+=	abseil-cpp-20240722.0.tar.gz:abseil \
		apple_support.1.16.0.tar.gz:apple_support \
		v0.1.1.zip:rules_android \
		rules_android_ndk-v0.1.2.tar.gz:rules_android_ndk \
		rules_apple.3.8.0.tar.gz:rules_apple \
		c8c38f8c710cbbf834283e4777916b68261b359c.zip:rules_cc \
		rules_java-6.0.0.tar.gz:rules_java \
		5.3.0-21.7.tar.gz:rules_proto \
		rules_python-0.34.0.tar.gz:rules_python \
		rules_swift.1.13.0.tar.gz:rules_swift \
		zlib-1.2.13.tar.xz:zlib \
		protobuf-27.3.tar.gz:protobuf \
		bazel-skylib-1.7.1.tar.gz:bazel_skylib \
		platforms-0.0.7.tar.gz:platforms \
		rules_license-0.0.3.tar.gz:rules_license \
		rules_pkg-0.7.0.tar.gz:rules_pkg

MASTER_SITES+=	https://github.com/abseil/abseil-cpp/releases/download/20240722.0/:abseil \
		https://github.com/bazelbuild/apple_support/releases/download/1.16.0/:apple_support \
		https://github.com/bazelbuild/rules_android/archive/:rules_android \
		https://github.com/bazelbuild/rules_android_ndk/releases/download/v0.1.2/:rules_android_ndk \
		https://github.com/bazelbuild/rules_apple/releases/download/3.8.0/:rules_apple \
		https://github.com/bazelbuild/rules_cc/archive/:rules_cc \
		https://github.com/bazelbuild/rules_java/releases/download/6.0.0/:rules_java \
		https://github.com/bazelbuild/rules_proto/archive/refs/tags/:rules_proto \
		https://github.com/bazelbuild/rules_python/releases/download/0.34.0/:rules_python \
		https://github.com/bazelbuild/rules_swift/releases/download/1.13.0/:rules_swift \
		https://github.com/madler/zlib/releases/download/v1.2.13/:zlib \
		https://github.com/protocolbuffers/protobuf/releases/download/v27.3/:protobuf \
		https://mirror.bazel.build/github.com/bazelbuild/bazel-skylib/releases/download/1.7.1/:bazel_skylib \
		https://mirror.bazel.build/github.com/bazelbuild/platforms/releases/download/0.0.7/:platforms \
		https://mirror.bazel.build/github.com/bazelbuild/rules_license/releases/download/0.0.3/:rules_license \
		https://mirror.bazel.build/github.com/bazelbuild/rules_pkg/releases/download/0.7.0/:rules_pkg
