DISTFILES+=	abseil-cpp-20240116.1.tar.gz:abseil \
		apple_support.1.12.0.tar.gz:apple_support \
		v0.1.1.zip:rules_android \
		44dcd014f4b126f8941c29ff1b25e1584bd3eb26.zip:rules_android_ndk \
		rules_apple.3.1.1.tar.gz:rules_apple \
		c8c38f8c710cbbf834283e4777916b68261b359c.zip:rules_cc \
		rules_java-6.0.0.tar.gz:rules_java \
		5.3.0-21.7.tar.gz:rules_proto \
		rules_python-0.0.1.tar.gz:rules_python \
		rules_swift.1.13.0.tar.gz:rules_swift \
		zlib-1.2.13.tar.xz:zlib \
		protobuf-27.0.tar.gz:protobuf \
		bazel-skylib-1.4.1.tar.gz:skylib \
		platforms-0.0.7.tar.gz:platforms \
		rules_license-0.0.3.tar.gz:rules_license \
		rules_pkg-0.7.0.tar.gz:rules_pkg

MASTER_SITES+=	https://github.com/abseil/abseil-cpp/releases/download/20240116.1/:abseil \
		https://github.com/bazelbuild/apple_support/releases/download/1.12.0/:apple_support \
		https://github.com/bazelbuild/rules_android/archive/:rules_android \
		https://github.com/bazelbuild/rules_android_ndk/archive/:rules_android_ndk \
		https://github.com/bazelbuild/rules_apple/releases/download/3.1.1/:rules_apple \
		https://github.com/bazelbuild/rules_cc/archive/:rules_cc \
		https://github.com/bazelbuild/rules_java/releases/download/6.0.0/:rules_java \
		https://github.com/bazelbuild/rules_proto/archive/refs/tags/:rules_proto \
		https://github.com/bazelbuild/rules_python/releases/download/0.0.1/:rules_python \
		https://github.com/bazelbuild/rules_swift/releases/download/1.13.0/:rules_swift \
		https://github.com/madler/zlib/releases/download/v1.2.13/:zlib \
		https://github.com/protocolbuffers/protobuf/releases/download/v27.0/:protobuf \
		https://mirror.bazel.build/github.com/bazelbuild/bazel-skylib/releases/download/1.4.1/:skylib \
		https://mirror.bazel.build/github.com/bazelbuild/platforms/releases/download/0.0.7/:platforms \
		https://mirror.bazel.build/github.com/bazelbuild/rules_license/releases/download/0.0.3/:rules_license \
		https://mirror.bazel.build/github.com/bazelbuild/rules_pkg/releases/download/0.7.0/:rules_pkg
