PKGNAMEPREFIX=	ja-fcitx5-

COMMENT=	Mozc engine for Fcitx

DATADIR=	${PREFIX}/share/fcitx5/${PORTNAME}

MASTERDIR=	${.CURDIR}/../../japanese/mozc-server
FILESDIR=	${.CURDIR}/files
SUB_FILES=	pkg-message

BUILD_MOZC_LIST=	fcitx5_mozc

.include "${MASTERDIR}/Makefile"
