# Created by: Daichi GOTO <daichi@FreeBSD.org>
# $FreeBSD: japanese/mozc-tool/Makefile 2487 2020-05-04 00:16:42Z  $

PKGNAMESUFFIX=	-tool

COMMENT=	Mozc tool for IBus, SCIM, and others
DATADIR=	${PREFIX}/share/${PORTNAME}${PKGNAMESUFFIX}

MASTERDIR=	${.CURDIR}/../../japanese/mozc-server
BUILD_MOZC_LIST=	mozc_tool

.include "${MASTERDIR}/Makefile"
