PKGNAMESUFFIX=	-tool

COMMENT=	Mozc tool for IBus, SCIM, and others
DATADIR=	${PREFIX}/share/${PORTNAME}${PKGNAMESUFFIX}

MASTERDIR=	${.CURDIR}/../../japanese/mozc-server.new
BUILD_MOZC_LIST=	mozc_tool

.include "${MASTERDIR}/Makefile"
