# Created by: TAKANO, Yuji
# $FreeBSD: japanese/mozc-el/Makefile 2487 2020-05-04 00:16:42Z  $

PORTREVISION=	1
PKGNAMESUFFIX=	-el${EMACS_PKGNAMESUFFIX}

COMMENT=	Emacs input method for Mozc

MASTERDIR=	${.CURDIR}/../../japanese/mozc-server
PKGMESSAGE=	${.CURDIR}/pkg-message

BUILD_MOZC_LIST=mozc_el

.include "${MASTERDIR}/Makefile"
