# Created by: Koichiro IWAO <meta+ports@vmeta.jp>
# $FreeBSD: japanese/uim-mozc/Makefile 2487 2020-05-04 00:16:42Z  $

PKGNAMEPREFIX=	ja-uim-

COMMENT=	Mozc engine for uim

MASTERDIR=	${.CURDIR}/../../japanese/mozc-server
FILESDIR=	${.CURDIR}/files
DATADIR=	${PREFIX}/share/uim
SUB_FILES=	pkg-message

BUILD_MOZC_LIST=uim_mozc

.include "${MASTERDIR}/Makefile"
