--- src/libaudtag/util.h.orig	2015-11-07 23:03:12 UTC
+++ src/libaudtag/util.h
@@ -147,7 +147,30 @@ enum {
     GENRE_PUNK_ROCK,
     GENRE_DRUM_SOLO,
     GENRE_A_CAPELLA,
-    GENRE_EURO_HOUSE
+    GENRE_EURO_HOUSE,
+    GENRE_DANCE_HALL,
+    GENRE_GOA,
+    GENRE_DRUM_BASS,
+    GENRE_CLUB_HOUSE,
+    GENRE_HARDCORE,
+    GENRE_TERROR,
+    GENRE_INDIE,
+    GENRE_BRITPOP,
+    GENRE_NEGERPUNK,
+    GENRE_POLSK_PUNK,
+    GENRE_BEAT,
+    GENRE_CHRISTIAN_GANGSTA_RAP,
+    GENRE_HEAVY_METAL,
+    GENRE_BLACK_METAL,
+    GENRE_CROSSOVER,
+    GENRE_CONTEMPORARY_CHRISTIAN,
+    GENRE_CHRISTIAN_ROCK,
+    GENRE_MERENGUE,
+    GENRE_SALSA,
+    GENRE_THRASH_METAL,
+    GENRE_ANIME,
+    GENRE_JPOP,
+    GENRE_SYNTHPOP
 };
 
 const char *convert_numericgenre_to_text(int numericgenre);
