# Created by: Yoichi Asai <yatt@luna2.org>
# $FreeBSD: audio/timidity++-xaw/Makefile 2482 2020-05-03 21:35:50Z  $

PKGNAMESUFFIX=	-xaw

MAINTAINER=	ports@FreeBSD.org
COMMENT=	Xaw interface for TiMidity++

OPTIONS_DEFINE=	DOCS

MASTERDIR=	${.CURDIR}/../../audio/timidity++

.include "${MASTERDIR}/Makefile"
