# Created by: Yoichi Asai <yatt@msc.biglobe.ne.jp>
# $FreeBSD: audio/timidity++-motif/Makefile 2482 2020-05-03 21:35:50Z  $

PKGNAMESUFFIX=	-motif

MAINTAINER=	ports@FreeBSD.org
COMMENT=	Motif interface for TiMidity++

MASTERDIR=	${.CURDIR}/../../audio/timidity++

PLIST_FILES=	bin/${LINK} ${TIMID_LIBDIR}/if_motif.so

.include "${MASTERDIR}/Makefile"
