# Created by: Yoichi Asai <yatt@luna2.org>
# $FreeBSD: audio/timidity++-emacs/Makefile 2482 2020-05-03 21:35:50Z  $

PKGNAMESUFFIX=	-emacs

MAINTAINER=	ports@FreeBSD.org
COMMENT=	Emacs interface for TiMidity++

MASTERDIR=	${.CURDIR}/../../audio/timidity++

PLIST_FILES=	${TIMID_LIBDIR}/if_emacs.so \
		share/emacs/site-lisp/timidity.el

.include "${MASTERDIR}/Makefile"
