DISTFILES+=	abseil-cpp-${abseil_VERSION}.tar.gz:abseil \
		apple_support.${apple_support_VERSION}.tar.gz:apple_support \
		bazel_features-v${bazel_features_VERSION}.tar.gz:bazel_features \
		bazel-skylib-${bazel_skylib_VERSION}.tar.gz:bazel_skylib \
		googletest-${googletest_VERSION}.tar.gz:googletest \
		kotlin-compiler-${kotlin_compiler_VERSION}.zip:kotlin_compiler \
		platforms-${platforms_VERSION}.tar.gz:platforms \
		protobuf-${protobuf_VERSION}.tar.gz:protobuf \
		rules_android-v${rules_android_VERSION}.tar.gz:rules_android \
		rules_android_ndk-v${rules_android_ndk_VERSION}.tar.gz:rules_android_ndk \
		rules_apple.${rules_apple_VERSION}.tar.gz:rules_apple \
		rules_cc-${rules_cc_VERSION}.tar.gz:rules_cc \
		rules_go-v${rules_go_VERSION}.zip:rules_go \
		rules_java-${rules_java_VERSION}.tar.gz:rules_java \
		rules_kotlin-v${rules_kotlin_VERSION}.tar.gz:rules_kotlin \
		rules_license-${rules_license_VERSION}.tar.gz:rules_license \
		rules_pkg-${rules_pkg_VERSION}.tar.gz:rules_pkg \
		rules_proto-${rules_proto_VERSION}.tar.gz:rules_proto \
		rules_python-${rules_python_VERSION}.tar.gz:rules_python \
		rules_swift.${rules_swift_VERSION}.tar.gz:rules_swift \
		zlib-${zlib_VERSION}.tar.xz:zlib

MASTER_SITES+=	https://github.com/abseil/abseil-cpp/releases/download/${abseil_VERSION}/:abseil \
		https://github.com/bazelbuild/apple_support/releases/download/${apple_support_VERSION}/:apple_support \
		https://github.com/protocolbuffers/protobuf/releases/download/v${protobuf_VERSION}/:protobuf \
		https://github.com/bazel-contrib/bazel_features/releases/download/v${bazel_features_VERSION}/:bazel_features \
		https://github.com/bazelbuild/bazel-skylib/releases/download/${bazel_skylib_VERSION}/:bazel_skylib \
		https://github.com/google/googletest/releases/download/v${googletest_VERSION}/:googletest \
		https://github.com/JetBrains/kotlin/releases/download/v${kotlin_compiler_VERSION}/:kotlin_compiler \
		https://github.com/bazelbuild/platforms/releases/download/${platforms_VERSION}/:platforms \
		https://github.com/protocolbuffers/protobuf/releases/download/v${protobuf_VERSION}/:protobuf \
		https://github.com/bazelbuild/rules_android/releases/download/v${rules_android_VERSION}/:rules_android \
		https://github.com/bazelbuild/rules_android_ndk/releases/download/v${rules_android_ndk_VERSION}/:rules_android_ndk \
		https://github.com/bazelbuild/rules_apple/releases/download/${rules_apple_VERSION}/:rules_apple \
		https://github.com/bazelbuild/rules_cc/releases/download/${rules_cc_VERSION}/:rules_cc \
		https://github.com/bazelbuild/rules_go/releases/download/v${rules_go_VERSION}/:rules_go \
		https://github.com/bazelbuild/rules_java/releases/download/${rules_java_VERSION}/:rules_java \
		https://github.com/bazelbuild/rules_kotlin/releases/download/v${rules_kotlin_VERSION}/:rules_kotlin \
		https://github.com/bazelbuild/rules_license/releases/download/${rules_license_VERSION}/:rules_license \
		https://github.com/bazelbuild/rules_pkg/releases/download/${rules_pkg_VERSION}/:rules_pkg \
		https://github.com/bazelbuild/rules_proto/releases/download/${rules_proto_VERSION}/:rules_proto \
		https://github.com/bazelbuild/rules_python/releases/download/${rules_python_VERSION}/:rules_python \
		https://github.com/bazelbuild/rules_swift/releases/download/${rules_swift_VERSION}/:rules_swift \
		https://github.com/madler/zlib/releases/download/v${zlib_VERSION}/:zlib

abseil_VERSION=	20240722.0
apple_support_VERSION=	1.16.0
bazel_features_VERSION=	1.13.0
bazel_skylib_VERSION=	1.7.1
googletest_VERSION=	1.15.2
kotlin_compiler_VERSION=	1.9.22
platforms_VERSION=	0.0.10
protobuf_VERSION=	27.3
rules_android_VERSION=	0.5.1
rules_android_ndk_VERSION=	0.1.2
rules_apple_VERSION=	3.5.1
rules_cc_VERSION=	0.0.9
rules_go_VERSION=	0.48.0
rules_java_VERSION=	7.9.0
rules_kotlin_VERSION=	1.9.5
rules_license_VERSION=	0.0.7
rules_pkg_VERSION=	0.7.0
rules_proto_VERSION=	6.0.0
rules_python_VERSION=	0.34.0
rules_swift_VERSION=	1.18.0
zlib_VERSION=	1.3.1
