PORTNAME=	Calendar-Japanese-Holiday
PORTVERSION=	0.07
CATEGORIES=	japanese perl5
MASTER_SITES=	CPAN
PKGNAMEPREFIX=	ja-p5-

MAINTAINER=	kdeguchi@sz.tokoha-u.ac.jp
COMMENT=	Perl module for Calculate Japanese Holiday
WWW=	http://search.cpan.org/dist/Calendar-Japanese-Holiday/

LICENSE=	ART10 GPLv1+
LICENSE_COMB=	dual

USES=		perl5
USE_PERL5=	configure

.include <bsd.port.mk>
