# Created by: Yoichi Asai <yatt@msc.biglobe.ne.jp>
# $FreeBSD: audio/timidity++-slang/Makefile 2482 2020-05-03 21:35:50Z  $

PKGNAMESUFFIX=	-slang

MAINTAINER=	ports@FreeBSD.org
COMMENT=	Slang interface for TiMidity++

MASTERDIR=	${.CURDIR}/../../audio/timidity++

PLIST_FILES=	${TIMID_LIBDIR}/if_${INTERFACE}.so

.include "${MASTERDIR}/Makefile"
